In [3]:
%load_ext autoreload
%autoreload 2

import numpy as np
from pomdp import *
from helpers import *
from fractions import Fraction as frac

## Budget 1

10x10 grid with target at the bottom right

In [2]:
budget = 1
gridSize = (10, 10)
target = Node(9, 9)
strategies = list([  
    Strategy({ Action.DOWN: frac(1, 2), Action.RIGHT: frac(1, 2) }) 
])
enumerated_strategies = dict(enumerate(strategies, start=1))

pomdp = POMDP(gridSize=gridSize, target=target, model='grid', budget=budget)

# Assign strategies to the nodes
for node in pomdp.nodes: node.assign_strategy(enumerated_strategies[1], 1)
observations =  {n: n.strategy_id for n in pomdp.nodes if n != target}

# ---------------------------------------------------------
# get one specific utility value
# print(pomdp.utility(enumerated_strategies, assignments)[0])
# ---------------------------------------------------------

combinations_, U = pomdp.generate_points(enumerated_strategies, observations, sections=10, write_to_file=True)
plot_actions_3D(combinations_, U, actions = [Action.DOWN, Action.RIGHT])

# get the probability distribution of the actions that maximizes the utility
max_index = np.argmax(U)
approx = np.around(list(map(float, combinations_[max_index][0])), 2)

print('Max utility value: ')
print(combinations_[max_index][0])
print(approx)
print(U[max_index]) # 0.07480985633519664

Max utility value: 
[Fraction(0, 1) Fraction(5, 9) Fraction(4, 9) Fraction(0, 1)]
[0.   0.56 0.44 0.  ]
0.07480985633519664


11x11 grid with the target in the bottom middle

In [3]:
budget = 1
gridSize = (11, 11)
target = Node(10, 5)
strategies = list([ 
    Strategy({ Action.DOWN: frac(1, 3), Action.RIGHT: frac(1, 3), Action.LEFT: frac(1, 3) }) 
])
enumerated_strategies = dict(enumerate(strategies, start=1))

pomdp = POMDP(gridSize=gridSize, target=target, model='grid', budget=budget)

# Assign strategies to the nodes
for node in pomdp.nodes: node.assign_strategy(enumerated_strategies[1], 1)
observations =  {n: n.strategy_id for n in pomdp.nodes if n != target}

# ---------------------------------------------------------
# get one specific utility value
# print(pomdp.utility(enumerated_strategies, assignments)[0])
# ---------------------------------------------------------

combinations_, U = pomdp.generate_points(enumerated_strategies, observations, sections=10, write_to_file=True)
plot_actions_4D(combinations_, U, actions = [Action.DOWN, Action.RIGHT, Action.LEFT])

# get the probability distribution of the actions that maximizes the utility
max_index = np.argmax(U)
approx = np.around(list(map(float, combinations_[max_index][0])), 2)

print('Max utility value: ')
print(combinations_[max_index][0])
print(approx)
print(U[max_index]) # 0.07480985633519664

Max utility value: 
[Fraction(0, 1) Fraction(1, 3) Fraction(1, 3) Fraction(1, 3)]
[0.   0.33 0.33 0.33]
0.02203856749311295


10x10 grid with the target close to the bottom left.

In [5]:
budget = 1
gridSize = (10, 10)
target = Node(9, 1)
strategies = list([ 
    Strategy({ Action.DOWN: frac(1, 3), Action.RIGHT: frac(1, 3), Action.LEFT: frac(1, 3) }) 
])
enumerated_strategies = dict(enumerate(strategies, start=1))

pomdp = POMDP(gridSize=gridSize, target=target, model='grid', budget=budget)

# Assign strategies to the nodes
for node in pomdp.nodes: node.assign_strategy(enumerated_strategies[1], 1)
observations =  {n: n.strategy_id for n in pomdp.nodes if n != target}

# ---------------------------------------------------------
# get one specific utility value
# print(pomdp.utility(enumerated_strategies, assignments)[0])
# ---------------------------------------------------------

combinations_, U = pomdp.generate_points(enumerated_strategies, observations, sections=20, write_to_file=True)
plot_actions_4D(combinations_, U, actions = [Action.DOWN, Action.RIGHT, Action.LEFT])

# get the probability distribution of the actions that maximizes the utility
max_index = np.argmax(U)
approx = np.around(list(map(float, combinations_[max_index][0])), 2)

print('Max utility value: ')
print(combinations_[max_index][0])
print(approx)
print(U[max_index])

Max utility value: 
[Fraction(0, 1) Fraction(2, 19) Fraction(9, 19) Fraction(8, 19)]
[0.   0.11 0.47 0.42]
0.052440814232111506


5x5 grid with the target close to the bottom left.

In [4]:
budget = 1
gridSize = (5, 5)
target = Node(4, 1)
strategies = list([ 
    Strategy({ Action.DOWN: frac(1, 3), Action.RIGHT: frac(1, 3), Action.LEFT: frac(1, 3) }) 
])
enumerated_strategies = dict(enumerate(strategies, start=1))

pomdp = POMDP(gridSize=gridSize, target=target, model='grid', budget=budget)

# Assign strategies to the nodes
for node in pomdp.nodes: node.assign_strategy(enumerated_strategies[1], 1)
observations =  {n: n.strategy_id for n in pomdp.nodes if n != target}

# ---------------------------------------------------------
# get one specific utility value
# print(pomdp.utility(enumerated_strategies, assignments)[0])
# ---------------------------------------------------------

combinations_, U = pomdp.generate_points(enumerated_strategies, observations, sections=20, write_to_file=True)
plot_actions_4D(combinations_, U, actions = [Action.DOWN, Action.RIGHT, Action.LEFT])

# get the probability distribution of the actions that maximizes the utility
max_index = np.argmax(U)
approx = np.around(list(map(float, combinations_[max_index][0])), 2)

print('Max utility value: ')
print(combinations_[max_index][0])
print(approx)
print(U[max_index])

Max utility value: 
[Fraction(0, 1) Fraction(3, 19) Fraction(8, 19) Fraction(8, 19)]
[0.   0.16 0.42 0.42]
0.09977284235955096


20x20 grid with the target close to the bottom left.

In [9]:
budget = 1
gridSize = (20, 20)
target = Node(19, 1)
strategies = list([ 
    Strategy({ Action.DOWN: frac(1, 3), Action.RIGHT: frac(1, 3), Action.LEFT: frac(1, 3) }) 
])
enumerated_strategies = dict(enumerate(strategies, start=1))

pomdp = POMDP(gridSize=gridSize, target=target, model='grid', budget=budget)

# Assign strategies to the nodes
for node in pomdp.nodes: node.assign_strategy(enumerated_strategies[1], 1)
observations =  {n: n.strategy_id for n in pomdp.nodes if n != target}

# ---------------------------------------------------------
# get one specific utility value
# print(pomdp.utility(enumerated_strategies, assignments)[0])
# ---------------------------------------------------------

combinations_, U = pomdp.generate_points(enumerated_strategies, observations, sections=20, write_to_file=True)
plot_actions_4D(combinations_, U, actions = [Action.DOWN, Action.RIGHT, Action.LEFT])

# get the probability distribution of the actions that maximizes the utility
max_index = np.argmax(U)
approx = np.around(list(map(float, combinations_[max_index][0])), 2)

print('Max utility value: ')
print(combinations_[max_index][0])
print(approx)
print(U[max_index])

# Budget 2

10x10 grid with target close to the bottom left

In [95]:
budget = 2
gridSize = (10, 10)
target = Node(9, 1)
strategies = list([
    Strategy({ Action.RIGHT: frac(1, 3) }),
    Strategy({ Action.DOWN: frac(1, 3), Action.LEFT: frac(1, 3) }), 
])
enumerated_strategies = dict(enumerate(strategies, start=1))

pomdp = POMDP(gridSize=gridSize, target=target, model='grid', budget=budget)

# Assign strategies to the nodes
for node in pomdp.nodes: 
    if node.j < 1: node.assign_strategy(enumerated_strategies[1], 1)
    else: node.assign_strategy(enumerated_strategies[2], 2)

observations =  {n: n.strategy_id for n in pomdp.nodes if n != target}

# ---------------------------------------------------------
# get one specific utility value
# print(pomdp.utility(enumerated_strategies, assignments)[0])
# ---------------------------------------------------------

combinations_, U = pomdp.generate_points(enumerated_strategies, observations, sections=90, write_to_file=True)

# get the probability distribution of the actions that maximizes the utility
max_index = np.argmax(U)
print('Max utility value: ')

print(combinations_[max_index])
print([list(map(lambda x : round(float(x), 2), x)) for x in combinations_[max_index]])
print(U[max_index]) 

Max utility value: 
[[Fraction(0, 1) Fraction(1, 1) Fraction(0, 1) Fraction(0, 1)]
 [Fraction(0, 1) Fraction(0, 1) Fraction(52, 89) Fraction(37, 89)]]
[[0.0, 1.0, 0.0, 0.0], [0.0, 0.0, 0.58, 0.42]]
0.0723509908371792


In [97]:
budget = 2
gridSize = (10, 10)
target = Node(9, 1)
strategies = list([
    Strategy({ Action.RIGHT: frac(1, 3) }),
    Strategy({ Action.DOWN: frac(1, 3), Action.LEFT: frac(1, 3) }), 
])
enumerated_strategies = dict(enumerate(strategies, start=1))

pomdp = POMDP(gridSize=gridSize, target=target, model='grid', budget=budget)

# Assign strategies to the nodes
for node in pomdp.nodes: 
    if node.j <= 1: node.assign_strategy(enumerated_strategies[1], 1)
    else: node.assign_strategy(enumerated_strategies[2], 2)

observations =  {n: n.strategy_id for n in pomdp.nodes if n != target}

# ---------------------------------------------------------
# get one specific utility value
# print(pomdp.utility(enumerated_strategies, assignments)[0])
# ---------------------------------------------------------

combinations_, U = pomdp.generate_points(enumerated_strategies, observations, sections=90, write_to_file=True)

# get the probability distribution of the actions that maximizes the utility
max_index = np.argmax(U)
print('Max utility value: ')

print(combinations_[max_index])
print([list(map(lambda x : round(float(x), 2), x)) for x in combinations_[max_index]])
print(U[max_index]) 

Max utility value: 
[[Fraction(0, 1) Fraction(1, 1) Fraction(0, 1) Fraction(0, 1)]
 [Fraction(0, 1) Fraction(0, 1) Fraction(53, 89) Fraction(36, 89)]]
[[0.0, 1.0, 0.0, 0.0], [0.0, 0.0, 0.6, 0.4]]
0.06463233843503492


In [96]:
budget = 2
gridSize = (10, 10)
target = Node(9, 1)
strategies = list([
    Strategy({ Action.DOWN: frac(1, 3), Action.RIGHT: frac(1, 3) }), 
    Strategy({ Action.LEFT: frac(1, 3) }),
])
enumerated_strategies = dict(enumerate(strategies, start=1))

pomdp = POMDP(gridSize=gridSize, target=target, model='grid', budget=budget)

# Assign strategies to the nodes
for node in pomdp.nodes: 
    if node.j < 1: node.assign_strategy(enumerated_strategies[1], 1)
    else: node.assign_strategy(enumerated_strategies[2], 2)

observations =  {n: n.strategy_id for n in pomdp.nodes if n != target}

# ---------------------------------------------------------
# get one specific utility value
# print(pomdp.utility(enumerated_strategies, assignments)[0])
# ---------------------------------------------------------

combinations_, U = pomdp.generate_points(enumerated_strategies, observations, sections=90, write_to_file=True)

# get the probability distribution of the actions that maximizes the utility
max_index = np.argmax(U)
print('Max utility value: ')

print(combinations_[max_index])
print([list(map(lambda x : round(float(x), 2), x)) for x in combinations_[max_index]])
print(U[max_index]) 

Max utility value: 
[[Fraction(0, 1) Fraction(21, 89) Fraction(68, 89) Fraction(0, 1)]
 [Fraction(0, 1) Fraction(0, 1) Fraction(0, 1) Fraction(1, 1)]]
[[0.0, 0.24, 0.76, 0.0], [0.0, 0.0, 0.0, 1.0]]
0.0636816547896828


In [7]:
budget = 2
gridSize = (20, 20)
target = Node(19, 1)
strategies = list([
    Strategy({ Action.DOWN: frac(1, 3), Action.RIGHT: frac(1, 3) }), 
    Strategy({ Action.LEFT: frac(1, 3) }),
])
enumerated_strategies = dict(enumerate(strategies, start=1))

pomdp = POMDP(gridSize=gridSize, target=target, model='grid', budget=budget)

# Assign strategies to the nodes
for node in pomdp.nodes: 
    if node.j <= 1: node.assign_strategy(enumerated_strategies[1], 1)
    else: node.assign_strategy(enumerated_strategies[2], 2)

observations =  {n: n.strategy_id for n in pomdp.nodes if n != target}

# ---------------------------------------------------------
# get one specific utility value
# print(pomdp.utility(enumerated_strategies, assignments)[0])
# ---------------------------------------------------------

combinations_, U = pomdp.generate_points(enumerated_strategies, observations, sections=20, write_to_file=True)

# get the probability distribution of the actions that maximizes the utility
max_index = np.argmax(U)
print('Max utility value: ')

print(combinations_[max_index])
print([list(map(lambda x : round(float(x), 2), x)) for x in combinations_[max_index]])
print(U[max_index]) 

In [ ]:
budget = 2
gridSize = (20, 20)
target = Node(19, 1)
strategies = list([
    Strategy({ Action.LEFT: frac(1, 3), Action.RIGHT: frac(1, 3) }), 
    Strategy({ Action.DOWN: frac(1, 3) }),
])
enumerated_strategies = dict(enumerate(strategies, start=1))

pomdp = POMDP(gridSize=gridSize, target=target, model='grid', budget=budget)

# Assign strategies to the nodes
for node in pomdp.nodes: 
    if node.i == 19: node.assign_strategy(enumerated_strategies[1], 1)
    else: node.assign_strategy(enumerated_strategies[2], 2)

observations =  {n: n.strategy_id for n in pomdp.nodes if n != target}

# ---------------------------------------------------------
# get one specific utility value
# print(pomdp.utility(enumerated_strategies, assignments)[0])
# ---------------------------------------------------------

combinations_, U = pomdp.generate_points(enumerated_strategies, observations, sections=20, write_to_file=True)

# get the probability distribution of the actions that maximizes the utility
max_index = np.argmax(U)
print('Max utility value: ')

print(combinations_[max_index])
print([list(map(lambda x : round(float(x), 2), x)) for x in combinations_[max_index]])
print(U[max_index]) 

Max utility value: 
[[Fraction(0, 1) Fraction(1, 19) Fraction(0, 1) Fraction(18, 19)]
 [Fraction(0, 1) Fraction(0, 1) Fraction(1, 1) Fraction(0, 1)]]
[[0.0, 0.05, 0.0, 0.95], [0.0, 0.0, 1.0, 0.0]]
0.06618321274047534
